name: simple-java-maven-app-jenkins-workflow

on: push

jobs:
  simple-java-maven-app-jenkins-docs-build:
    runs-on: ubuntu-latest

    env:
      APP_NAME: 'simple-java-maven-app-jenkins-docs'
      IMAGE_NAME: 'registry/simple-java-maven-app-jenkins-docs'

    steps:
    - uses: actions/checkout@v4

    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.7.0
      with:
        checkout-fetch-depth: 0
        java-version: 17
        java-distribution: temurin
        maven-version: 3.9.2

    - name: Build
      run: mvn -B -DskipTests clean package

    - name: Test
      run: mvn test

    - name: Confirm Build Artifact
      run: ls -lah target/my-app-1.0-SNAPSHOT.jar && echo 'Build Step Executed!'

    - name: Setup docker context for buildx
      id: buildx-context
      run: docker context create builders || docker context use builders

    - name: Copy ca cert
      run: |
        echo "
          -----BEGIN CERTIFICATE-----
          MIIFHjCCAwagAwIBAgIUahuxCqQcQBCFdHXQ2e6VXCKydmswDQYJKoZIhvcNAQEL
          BQAwFjEUMBIGA1UEAwwLMzQuMjcuNTkuNTMwHhcNMjQwOTI1MDMwNzQwWhcNMjUw
          OTI1MDMwNzQwWjAWMRQwEgYDVQQDDAszNC4yNy41OS41MzCCAiIwDQYJKoZIhvcN
          AQEBBQADggIPADCCAgoCggIBAPtCtrvztIZG3gATSb3DMJcNzYJAh9sElyyM7LEq
          GvIEquqrutky5jZLzy/EaUaoB9EV2nau31/t+Evnk4q/q04PAXcUqfrW7Y9E14ya
          0rc0hPuaBXfcJsyTBTGyu8MEP78W6nCZt/VK+LxXV8xOZWj1kWNic7lCbJO2vomm
          7pizhBN/CulQTtwDlMe6xrEmCbTcff8TUC0xBDnKEX59daDCmlCTLUpw7eAiyFvb
          6U+XbI49B92NKGzzsYwrFD4c6rMjEKO026f8On1V60KpGQSVTC7mzkjChR1NUNYf
          i3NKP7LXL4KvN1/WcmSBD/07X/cnf6faKW+1uy8Mt1lx8hOUMae3Iw6L0lanoc5R
          zKtzy70sMk+fAjQBfllY0/cQHFqVduvXM2hyanejh3/5+HD8X6PxXQxqNWrf85+5
          Q0NjEGh5jO96hrn7sEoYpBZUrfpK+goaIf7OBPQGs+ZxYGk1JXdU8nNxcti3JZ7E
          y8it8flLjwtXb4tmUdNyR3HMEhyMQF3vcaawmQsmMDnUNBRFTz9blaYV9Kjc0Ia2
          EBhQoFhhMkISlaAEuT+h3g+J4iZzQOfrA/VHNO4kp21XqAYEA+LmhE1toMip3AMn
          KpZqKcW0sZ6Czfx+vlr8YEFrPZSI5FqEMTdsKjaPXTL8p3xQD0MJomYep3NSuYqH
          SPEZAgMBAAGjZDBiMB0GA1UdDgQWBBQtDtEXf0OyWz95kUHICo/Gabk5WTAfBgNV
          HSMEGDAWgBQtDtEXf0OyWz95kUHICo/Gabk5WTAPBgNVHRMBAf8EBTADAQH/MA8G
          A1UdEQQIMAaHBCIbOzUwDQYJKoZIhvcNAQELBQADggIBAERlYMK6BCSs5hlBr3aj
          S4juIsGB6FREr5OkhzISOomGfB6fxAjnbYbG9JUtRhqej65gqaNBv0R2otFLoWvU
          xeNCCCbuKK+UkNdHr0dJJV+zei8VjNsBmUqrWFLO1TlQeP3dbm8OiVq/kkCKMQdp
          2wEroWWbNa3AeGD+ZjSMGC1BNXy7hcy3k5aDW18mpneONe3wNbN8U3T9gJVAxsB5
          V/cLzfuka15cWqLGX3qVY/b0EOEfHIzsgYz9Df2L8iK+GPeBdRRcoUanlN7GMq1/
          C3goc+nKIaZUw8adGHr62So/IWylydHoybp376MQSGpd+NZJszuhp8pfYP6cM5lj
          X8SRY24ie2QHShxvbmgRP7i/WtWlWcIEtGnXaujms4XsiuuVmUpPdTrIyaiITw9m
          g9KL1ibA8oHu8BcUmDnpogidKiXRoYSObVru7/W4/HO6FmJewgGpAyE9q6sbWGnK
          D0JTDCr/qPvqXsRGQsnCAaj6yY7NS+HBzuf2cWPcotUULN1WO1vpVOqqken8mfiE
          BBkNsYUE3h6uuaIxIeowXaK7f9Z6owsnE8/PQ1OwOeci5ncwYmPMTcyzIUxL0KJW
          rtugNQ4nzeCPudEcHouXIG6KJJa54EdcutQuRbG1SW1RvRyZ7mBWjKyRRjHXZfr8
          M7f4I/RxLITPEw8wNWUPFYP8
          -----END CERTIFICATE-----
      " | sudo tee /etc/ssl/certs/ca-certificates.crt

    - name: Create BuildKit Configuration
      run: |
        cat <<EOF > buildkitd.toml
        [registry."34.27.59.53:5000"]
          http = false
          insecure = false
          ca=["/etc/ssl/certs/ca-certificates.crt"]
        EOF

    - name: Setup Docker Buildx
      id: setup_docker_buildx
      uses: docker/setup-buildx-action@v1
      with:
        endpoint: builders
        buildkitd-flags: --debug
        config: buildkitd.toml

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: 34.27.59.53:5000
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: '${{ env.IMAGE_NAME }}:latest'
