name: simple-java-maven-app-jenkins-workflow

on: push

jobs:
  simple-java-maven-app-jenkins-docs-build:
    runs-on: ubuntu-latest

    env:
      APP_NAME: 'simple-java-maven-app-jenkins-docs'
      DOCKER_USER: 'registry'
      DOCKER_PASS: 'docker' # Secret name to use to sign into Docker registry
      IMAGE_NAME: 'registry/simple-java-maven-app-jenkins-docs'

    steps:
    - uses: actions/checkout@v4

    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.7.0
      with:
        checkout-fetch-depth: 0
        java-version: 17
        java-distribution: temurin
        maven-version: 3.9.2

    - name: Build
      run: mvn -B -DskipTests clean package

    - name: Test
      run: mvn test

    - name: Confirm Build Artifact
      run: ls -lah target/my-app-1.0-SNAPSHOT.jar && echo 'Build Step Executed!'

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: https://34.27.59.53:5000
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: '${{ env.IMAGE_NAME }}:latest'

