jobs:
  simple-java-maven-app-jenkins-docs-build:
    env:
      APP_NAME: 'simple-java-maven-app-jenkins-docs'
      DOCKER_USER: 'registry'
      DOCKER_PASS: 'docker' # Secret name to use to sign into Docker registry
      IMAGE_NAME: '${{ env.DOCKER_USER }}/${{ env.APP_NAME }}'

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build
      run: mvn -B -DskipTests clean package

    - name: Test
      run: mvn test

    - name: Confirm Build Artifact
      run: ls -lah target/my-app-1.0-SNAPSHOT.jar && echo 'Build Step Executed!'

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: https://<external_ip_of_your_node>:5000
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: '${{ env.IMAGE_NAME }}:latest'

