name: simple-java-maven-app-jenkins-workflow

on: push

jobs:
  simple-java-maven-app-jenkins-docs-build:
    # runs-on: ubuntu-latest
    runs-on: self-hosted

    env:
      APP_NAME: 'simple-java-maven-app-jenkins-docs'
      IMAGE_NAME: '35.192.185.56:5000/simple-java-maven-app-jenkins-docs'

    steps:
    - uses: actions/checkout@v4

    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.7.0
      with:
        checkout-fetch-depth: 0
        java-version: 17
        java-distribution: temurin
        maven-version: 3.9.2

    - name: Build
      run: mvn -B -DskipTests clean package

    - name: Test
      run: mvn test

    - name: Confirm Build Artifact
      run: ls -lah target/my-app-1.0-SNAPSHOT.jar && echo 'Build Step Executed!'

    - name: Save Docker certificate
      env:
        CERT: ${{ secrets.DOCKER_CERT }}
      shell: bash
      run: |
          echo "$CERT" >> /tmp/ca-certificates.crt
          sudo mkdir -p /etc/docker/certs.d/35.192.185.56:5000
          sudo cp /tmp/ca-certificates.crt /etc/docker/certs.d/35.192.185.56:5000/ca.crt
          sudo cp /tmp/ca-certificates.crt /usr/local/share/ca-certificates/ca.crt
          sudo update-ca-certificates

    - name: Login to Production Registry
      uses: docker/login-action@v3
      with:
        registry: 35.192.185.56:5000
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: '${{ env.IMAGE_NAME }}:latest'
