name: simple-java-maven-app-jenkins-workflow

on: push

jobs:
  simple-java-maven-app-jenkins-docs-build:
    runs-on: ubuntu-latest

    env:
      APP_NAME: 'simple-java-maven-app-jenkins-docs'
      IMAGE_NAME: 'registry/simple-java-maven-app-jenkins-docs'

    steps:
    - uses: actions/checkout@v4

    - name: Save Docker certificate
      env:
        CERT: ${{ secrets.DOCKER_CERT }}
        KEY: ${{ secrets.DOCKER_KEY }}
      shell: bash
      run: |
          echo "$CERT" >> /tmp/ca-certificates.crt
          echo "$KEY" >> /tmp/ca-certificates.key

    - name: Setup docker context for buildx
      id: buildx-context
      run: docker context create builders || docker context use builders

    - name: Setup Docker Buildx
      id: setup_docker_buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: v0.7.0-rc1
        endpoint: builders
        config-inline: |
          [registry."34.27.59.53:5000"]
            mirrors = ["34.27.59.53:5000"]
            ca=["/tmp/ca-certificates.crt"]
            [[registry."34.27.59.53:5000".keypair]]
             key="/tmp/ca-certificates.key"
             cert="/tmp/ca-certificates.crt"

    - name: Login to Production Registry
      uses: docker/login-action@v3
      with:
        registry: 34.27.59.53:5000
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: '${{ env.IMAGE_NAME }}:latest'
